// Generated by Xata Codegen 0.26.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "library",
    columns: [
      { name: "book-name", type: "string" },
      { name: "author", type: "string" },
      { name: "size", type: "string" },
      { name: "image", type: "file[]" },
      { name: "bookfile", type: "file[]" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Library = InferredTypes["library"];
export type LibraryRecord = Library & XataRecord;

export type DatabaseSchema = {
  library: LibraryRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://AbuTuraab-s-workspace-5ltcb8.us-east-1.xata.sh/db/library",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
